export enum CONFIG {
  BOT_TOKEN = "BOT_TOKEN",
  DAILY_NOTIFICATION = "DAILY_NOTIFICATION",
  CURRENCY = "CURRENCY",
  REGISTER_LINK="REGISTER_LINK",
  PORT="PORT",
  MEXICO_BOT_LINK="MEXICO_BOT_LINK",
  COLUMBIA_BOT_LINK="COLUMBIA_BOT_LINK",
  CHILE_BOT_LINK="CHILE_BOT_LINK",
  ECUADOR_BOT_LINK="ECUADOR_BOT_LINK",
  PERU_BOT_LINK="PERU_BOT_LINK",
  MEXICO_TELEGRAM_CHANNEL="MEXICO_TELEGRAM_CHANNEL",
  COLUMBIA_TELEGRAM_CHANNEL="COLUMBIA_TELEGRAM_CHANNEL",
  CHILE_TELEGRAM_CHANNEL="CHILE_TELEGRAM_CHANNEL",
  ECUADOR_TELEGRAM_CHANNEL="ECUADOR_TELEGRAM_CHANNEL",
  PERU_TELEGRAM_CHANNEL="PERU_TELEGRAM_CHANNEL"
}
