export enum CONFIG {
  BOT_TOKEN = "BOT_TOKEN",
  DAILY_NOTIFICATION = "DAILY_NOTIFICATION",
  CURRENCY = "CURRENCY",
  REGISTER_LINK="REGISTER_LINK",
  VIP_CANAL_LINK="VIP_CANAL_LINK",
  PORT="PORT"
}
